name: publish to github packages
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - uses: actions/checkout@v2
        name: Checkout [main]
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@csdev'
      - run: npm ci

      - name: Publish to GitHub Packages
        run: npm run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.TOKEN }}
